import type { Conversation, Identity, Message, VaultSettings } from "./types";

const HOUR = 60 * 60 * 1000;

function fp(seed: string): string {
  const map: Record<string, string> = {
    calder: "A91C 4E20 7B6D 11F8 93AA 0C44 51D2 6E7B",
    voss: "3F18 90BB 2C71 44AE 19D0 6A55 88C3 01F2",
    ops: "C0DE 12AB 9F44 70E1 55AA 2190 B3C8 4D6E",
    relay: "1111 8E2A 90CC 44D1 77AB 02F9 3C10 6AA1",
    notes: "BEEF 0144 90AA 33C1 78D2 6E01 4F19 A3C0",
  };
  return map[seed] ?? "0000 0000 0000 0000 0000 0000 0000 0000";
}

export const defaultSettings = (): VaultSettings => ({
  screenshotShield: true,
  stealth: true,
  coverTraffic: true,
  readReceipts: false,
  defaultTtl: 72,
  autoLockMinutes: 0,
});

export function buildSeed(identity: Identity): {
  conversations: Conversation[];
  messages: Record<string, Message[]>;
} {
  const now = Date.now();
  const you: Conversation["members"][number] = {
    id: identity.id,
    name: identity.callsign,
    fingerprint: identity.fingerprint,
    verified: true,
    hue: 0,
    role: "admin",
  };

  const calder = {
    id: "p-calder",
    name: "N. Calder",
    fingerprint: fp("calder"),
    verified: true,
    hue: 1,
    role: "member" as const,
  };
  const voss = {
    id: "p-voss",
    name: "A. Voss",
    fingerprint: fp("voss"),
    verified: false,
    hue: 2,
    role: "member" as const,
  };
  const relay = {
    id: "p-relay",
    name: "Relay",
    fingerprint: fp("relay"),
    verified: true,
    hue: 3,
    role: "member" as const,
  };
  const kirk = {
    id: "p-kirk",
    name: "M. Kirk",
    fingerprint: "77AA 12C0 90E1 44B2 19D8 6F03 2A11 C4E9",
    verified: true,
    hue: 4,
    role: "member" as const,
  };

  const conversations: Conversation[] = [
    {
      id: "c-ops",
      kind: "group",
      title: "GhostWeb Ops",
      subtitle: "MLS · 4 members · PQ ratchet",
      hue: 3,
      verified: true,
      muted: false,
      archived: false,
      pinned: true,
      unread: 0,
      ttlHours: 72,
      lastAt: now - 12 * 60 * 1000,
      lastPreview: "I'll send it sealed. No receipts.",
      members: [you, calder, voss, kirk],
    },
    {
      id: "c-calder",
      kind: "direct",
      title: "N. Calder",
      subtitle: "Verified · last hop 40ms",
      hue: 1,
      verified: true,
      muted: false,
      archived: false,
      pinned: false,
      unread: 1,
      ttlHours: 24,
      lastAt: now - 4 * 60 * 1000,
      lastPreview: "Keys rotated. You're clear to drop.",
      members: [you, calder],
    },
    {
      id: "c-drop",
      kind: "dead-drop",
      title: "Dead drop",
      subtitle: "One-shot · no sender copy",
      hue: 5,
      verified: true,
      muted: false,
      archived: false,
      pinned: false,
      unread: 1,
      ttlHours: 24,
      lastAt: now - 50 * 60 * 1000,
      lastPreview: "Sealed packet waiting",
      members: [you, relay],
    },
    {
      id: "c-voss",
      kind: "direct",
      title: "A. Voss",
      subtitle: "Unverified fingerprint",
      hue: 2,
      verified: false,
      muted: false,
      archived: false,
      pinned: false,
      unread: 0,
      ttlHours: 1,
      lastAt: now - 5 * HOUR,
      lastPreview: "Can you confirm the Berlin window?",
      members: [you, voss],
    },
    {
      id: "c-notes",
      kind: "direct",
      title: "Fork notes",
      subtitle: "Independent Android fork",
      hue: 6,
      verified: true,
      muted: false,
      archived: false,
      pinned: false,
      unread: 0,
      ttlHours: 0,
      lastAt: now - 26 * HOUR,
      lastPreview: "What GhostWire hardens over Wire Android.",
      members: [you, { id: "p-notes", name: "Vault", fingerprint: fp("notes"), verified: true, hue: 6 }],
    },
  ];

  const msg = (
    partial: Omit<Message, "id" | "delivered"> & { id: string },
  ): Message => ({
    delivered: true,
    ...partial,
  });

  const messages: Record<string, Message[]> = {
    "c-ops": [
      msg({
        id: "m-ops-0",
        conversationId: "c-ops",
        kind: "system",
        fromId: "system",
        fromName: "Vault",
        body: "MLS group established · hybrid X25519 + ML-KEM-768 · epoch 14",
        at: now - 8 * HOUR,
        ttlHours: 0,
      }),
      msg({
        id: "m-ops-1",
        conversationId: "c-ops",
        kind: "text",
        fromId: calder.id,
        fromName: calder.name,
        body: "Vault rotation complete on EU-West. Old epoch keys zeroized.",
        at: now - 3 * HOUR,
        ttlHours: 72,
      }),
      msg({
        id: "m-ops-2",
        conversationId: "c-ops",
        kind: "text",
        fromId: identity.id,
        fromName: identity.callsign,
        body: "Confirmed. Cover profile stays diurnal until Friday.",
        at: now - 3 * HOUR + 4 * 60 * 1000,
        ttlHours: 72,
        mine: true,
        reaction: "ack",
      }),
      msg({
        id: "m-ops-3",
        conversationId: "c-ops",
        kind: "text",
        fromId: kirk.id,
        fromName: kirk.name,
        body: "Relay is holding ciphertext only. Retention 72h, then purge.",
        at: now - 40 * 60 * 1000,
        ttlHours: 72,
      }),
      msg({
        id: "m-ops-4",
        conversationId: "c-ops",
        kind: "text",
        fromId: voss.id,
        fromName: voss.name,
        body: "Berlin dead-drop window is 72 hours. I'll keep the packet sealed.",
        at: now - 18 * 60 * 1000,
        ttlHours: 72,
      }),
      msg({
        id: "m-ops-5",
        conversationId: "c-ops",
        kind: "text",
        fromId: identity.id,
        fromName: identity.callsign,
        body: "I'll send it sealed. No receipts.",
        at: now - 12 * 60 * 1000,
        ttlHours: 72,
        mine: true,
      }),
    ],
    "c-calder": [
      msg({
        id: "m-ca-0",
        conversationId: "c-calder",
        kind: "system",
        fromId: "system",
        fromName: "Vault",
        body: "Fingerprints matched · session sealed",
        at: now - 2 * 24 * HOUR,
        ttlHours: 0,
      }),
      msg({
        id: "m-ca-1",
        conversationId: "c-calder",
        kind: "text",
        fromId: calder.id,
        fromName: calder.name,
        body: "Don't put the handover in the group. Use a drop.",
        at: now - 55 * 60 * 1000,
        ttlHours: 24,
      }),
      msg({
        id: "m-ca-2",
        conversationId: "c-calder",
        kind: "text",
        fromId: identity.id,
        fromName: identity.callsign,
        body: "Understood. Timer 24h, sealed sender, no read receipts.",
        at: now - 50 * 60 * 1000,
        ttlHours: 24,
        mine: true,
      }),
      msg({
        id: "m-ca-3",
        conversationId: "c-calder",
        kind: "text",
        fromId: calder.id,
        fromName: calder.name,
        body: "Keys rotated. You're clear to drop.",
        at: now - 4 * 60 * 1000,
        ttlHours: 24,
      }),
    ],
    "c-drop": [
      msg({
        id: "m-dr-0",
        conversationId: "c-drop",
        kind: "system",
        fromId: "system",
        fromName: "Vault",
        body: "Dead drops are consumed once. The sender keeps a delivery marker, never the body.",
        at: now - 6 * HOUR,
        ttlHours: 0,
      }),
      msg({
        id: "m-dr-1",
        conversationId: "c-drop",
        kind: "dead-drop",
        fromId: relay.id,
        fromName: relay.name,
        body: "BERLIN-NODE · pickup after 21:00 · ignore if the seal is broken",
        at: now - 50 * 60 * 1000,
        ttlHours: 24,
        expiresAt: now + 23 * HOUR,
        sealed: true,
        consumed: false,
      }),
      msg({
        id: "m-dr-2",
        conversationId: "c-drop",
        kind: "dead-drop",
        fromId: identity.id,
        fromName: identity.callsign,
        body: "",
        at: now - 3 * HOUR,
        ttlHours: 1,
        sealed: false,
        consumed: true,
        mine: true,
      }),
    ],
    "c-voss": [
      msg({
        id: "m-vo-0",
        conversationId: "c-voss",
        kind: "system",
        fromId: "system",
        fromName: "Vault",
        body: "Safety number not verified. Compare fingerprints in person before sensitive traffic.",
        at: now - 30 * HOUR,
        ttlHours: 0,
      }),
      msg({
        id: "m-vo-1",
        conversationId: "c-voss",
        kind: "text",
        fromId: voss.id,
        fromName: voss.name,
        body: "Can you confirm the Berlin window?",
        at: now - 5 * HOUR,
        ttlHours: 1,
        expiresAt: now + 20 * 60 * 1000,
      }),
      msg({
        id: "m-vo-2",
        conversationId: "c-voss",
        kind: "text",
        fromId: identity.id,
        fromName: identity.callsign,
        body: "Not on this channel. I'll verify your fingerprint first.",
        at: now - 5 * HOUR + 6 * 60 * 1000,
        ttlHours: 1,
        mine: true,
      }),
    ],
    "c-notes": [
      msg({
        id: "m-no-0",
        conversationId: "c-notes",
        kind: "system",
        fromId: "system",
        fromName: "Vault",
        body: "Local briefing · nothing here leaves the device",
        at: now - 26 * HOUR,
        ttlHours: 0,
      }),
      msg({
        id: "m-no-1",
        conversationId: "c-notes",
        kind: "text",
        fromId: "p-notes",
        fromName: "Vault",
        body: "GhostWire is an independent Android client in the Wire protocol lineage. Package app.ghostwire. Delivery links to the public wire.com backend while keys stay in the local vault. It is not affiliated with Wire Swiss GmbH.",
        at: now - 26 * HOUR + 1000,
        ttlHours: 0,
      }),
      msg({
        id: "m-no-2",
        conversationId: "c-notes",
        kind: "text",
        fromId: "p-notes",
        fromName: "Vault",
        body: "Hardened vs stock Wire Android: zero identity, hybrid PQ (ML-KEM-768 + X25519), dead drops, duress PIN wipe, screenshot shield, stealth (no last-seen), FCM optional — works without Google Play Services — sealed P2P invite channels.",
        at: now - 26 * HOUR + 2000,
        ttlHours: 0,
      }),
      msg({
        id: "m-no-3",
        conversationId: "c-notes",
        kind: "text",
        fromId: "p-notes",
        fromName: "Vault",
        body: "Set a vault PIN and a second duress PIN in Vault. Built for GrapheneOS & custom ROMs, and Android devices with or without Google Play Services. The duress PIN destroys keys, messages, and contacts with no recovery.",
        at: now - 26 * HOUR + 3000,
        ttlHours: 0,
      }),
    ],
  };

  return { conversations, messages };
}

export const demoDevices = [
  { id: "d-here", label: "This device", platform: "GhostWire Android", current: true, verified: true, lastSeenAgo: "now" },
  { id: "d-pixel", label: "Pixel 8", platform: "GrapheneOS", verified: true, lastSeenAgo: "2h ago" },
  { id: "d-tab", label: "Tablet", platform: "GhostWire Android", verified: true, lastSeenAgo: "yesterday" },
];
